### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by CoreyH** [customerio/twilio-opt-out#2]
Hi there, I followed the instructions to the letter and am getting 
`retrieve customer ids -> status: 401` when I run this on Twilio Functions. 

I've checked the api keys twice, recreated them, confirmed there are no ip restrictions. 

What else can I do to debug? Thanks!

**Comment by dimitriskam** [comment]
Hi Corey, I'm sorry you are experiencing this issue. If your Customer.io account is based in EU you have to make a slight change to the API URLs in the code. Every instance of `beta-api.customer.io`  will have to be replaced with `beta-api-eu.customer.io` and every instance of `track.customer.io` will have to be replaced with `track-eu.customer.io` . Hopefully this solves the issue.

**Comment by CoreyH** [comment]
Thank you! That did seem to do the trick.
